title: Testlify Netlify
languageCode: en-us
baseurl: https://netlify.sprinkle.cloud/
theme: vec
menu:
  main:
    - Name: posts
      URL: /post
params:
  Avater: fizzbuzzclub-logo.png
  Description: Asdf
  SelfIntro: Just a test of netlify and hugo.

